In [5]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [6]:
data = pd.read_csv('50_Startups.csv')

In [7]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [8]:
print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [9]:
print(y)

[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ]


In [10]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [11]:
print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [12]:
print(y)

[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ]


In [13]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [15]:
print(y)

[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ]


In [16]:
le = LabelEncoder()
y = le.fit_transform(y)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [18]:
print(X_train)

[[1.0 0.0 0.0 63408.86 129219.61 46085.25]
 [1.0 0.0 0.0 38558.51 82982.09 174999.3]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 28663.76 127056.21 201126.82]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 23640.93 96189.63 148001.11]
 [1.0 0.0 0.0 0.0 116983.8 45173.06]
 [0.0 1.0 0.0 75328.87 144135.98 134050.07]
 [0.0 1.0 0.0 73994.56 122782.75 303319.26]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 27892.92 84710.77 164470.71]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 0.0 1.0 1000.23 124153.04 1903.93]
 [0.0 0.0 1.0 77044.01 99281.34 140574.81]
 [0.0 1.0 0.0 67532.53 105751.03 304768.73]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 1.0 0.0 55493.95 103057.49 214634.81]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 1.0 0.0 61994.48 115641.28 91131.24]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 66051.52 182645.56 118148.2]
 [1.0 0.0 0.0 22177.74 154806.14 28334.72]
 [1.0 0.0 0.0 46426.07 157693.92 210797.67]
 [0.0 1.0 0.

In [19]:
print(X_test)

[[0.0 0.0 1.0 72107.6 127864.55 353183.81]
 [0.0 0.0 1.0 46014.02 85047.44 205517.64]
 [1.0 0.0 0.0 28754.33 118546.05 172795.67]
 [0.0 0.0 1.0 20229.59 65947.93 185265.1]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 0.0 1.0 542.05 51743.15 0.0]
 [0.0 0.0 1.0 65605.48 153032.06 107138.38]
 [0.0 1.0 0.0 1315.46 115816.21 297114.46]
 [0.0 0.0 1.0 61136.38 152701.92 88218.23]]


In [20]:
print(y_train)

[17 10 28 13 30  7  0 23 27 36  8 32  4 25 26 45 16 35 19 39 21  5 15 31
 29 24 43 42  2 48 33 49 34 44 38 40 41 37  6 12]


In [21]:
print(y_test)

[22 14  9 11 47 46  1 20  3 18]


In [22]:
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [23]:
print("Preprocessed X_train:")
print(X_train)

Preprocessed X_train:
[[1.0 0.0 0.0 -0.32133038496226557 0.18700266744239274
  -1.3700842498314485]
 [1.0 0.0 0.0 -0.8955888632549127 -1.6137113933587277
  -0.28442172627772067]
 [0.0 0.0 1.0 0.024851552213493014 1.1432479184934816 0.7660716916733844]
 [0.0 1.0 0.0 -1.124243352148879 0.102749342455734 -0.06438621193773587]
 [0.0 0.0 1.0 0.21041946816397103 1.133148735616741 -1.758195776958278]
 [1.0 0.0 0.0 -1.2403142611108313 -1.0993455063779112 -0.5117896748200481]
 [1.0 0.0 0.0 -1.7866246546152684 -0.2895193240547929 -1.377766348852932]
 [0.0 1.0 0.0 -0.045874835892206874 0.7679187112767512
  -0.6292797489632387]
 [0.0 1.0 0.0 -0.07670896217898596 -0.06367998831873588
  0.7962376091160044]
 [1.0 0.0 0.0 0.3391969091012879 0.43139962169069607 0.36964711927627536]
 [0.0 1.0 0.0 -1.1420564374940392 -1.546388180897815 -0.3730892965608864]
 [0.0 0.0 1.0 0.4007761933045245 0.8045891979215861 0.6215319446209713]
 [0.0 0.0 1.0 -1.7635106720056613 -0.010314226695379883
  -1.7421616406599485]

In [24]:
print("Preprocessed X_test:")
print(X_test)

Preprocessed X_test:
[[0.0 0.0 1.0 -0.12031409362377804 0.1342300361414674 1.2161768879523378]
 [0.0 0.0 1.0 -0.7233019607567341 -1.5332766125686765
  -0.027408483585626957]
 [1.0 0.0 0.0 -1.1221504001228926 -0.22867770578706248
  -0.30297981600322904]
 [0.0 0.0 1.0 -1.3191457832961866 -2.277104486801802 -0.19796726817716548]
 [0.0 1.0 0.0 1.7592041984804023 -0.9063378617593095 1.677265618763361]
 [0.0 0.0 1.0 1.5496293810036323 -0.2237784415348105 1.468958024152071]
 [0.0 0.0 1.0 -1.7740986013339854 -2.8303077528201026 -1.758195776958278]
 [0.0 0.0 1.0 -0.2705694235034857 1.1143753625420354 -0.8559192291323562]
 [0.0 1.0 0.0 -1.756226126713052 -0.33499096116359056 0.7439832673577076]
 [0.0 0.0 1.0 -0.3738443699463997 1.1015181041935587 -1.0152571585125523]]


In [25]:
print("Preprocessed y_train:")
print(y_train)

Preprocessed y_train:
[17 10 28 13 30  7  0 23 27 36  8 32  4 25 26 45 16 35 19 39 21  5 15 31
 29 24 43 42  2 48 33 49 34 44 38 40 41 37  6 12]


In [26]:
print("Preprocessed y_test:")
print(y_test)

Preprocessed y_test:
[22 14  9 11 47 46  1 20  3 18]


In [27]:

max_profit_index = np.argmax(data['Profit'])
max_profit_row = data.iloc[max_profit_index, :]

min_profit_index = np.argmin(data['Profit'])
min_profit_row = data.iloc[min_profit_index, :]

print("Record of maximum profit:")
print(max_profit_row)

print("Record of minimum profit:")
print(min_profit_row)




Record of maximum profit:
R&D Spend           165349.2
Administration      136897.8
Marketing Spend     471784.1
State               New York
Profit             192261.83
Name: 0, dtype: object
Record of minimum profit:
R&D Spend                 0.0
Administration       116983.8
Marketing Spend      45173.06
State              California
Profit                14681.4
Name: 49, dtype: object


In [35]:
preprocessed_data = pd.DataFrame(X, columns=['R&D Spend', 'Administration', 'Marketing Spend', 'State_Florida', 'State_New York', 'State_California'])
preprocessed_data['Profit'] = data.iloc[:, -1].values
preprocessed_data.to_csv('preprocessed_data.csv', index=False)